version: '3'

services:
  backend:
    image: sm-backend
    build:
      context: src
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/opt/backend/
      - ./poetry.lock:/opt/poetry.lock
      - ./pyproject.toml:/opt/pyproject.toml
    ports:
      - "8000:8000"

  database:
    image: postgres:13-alpine
    command: -p 5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"